apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    generator: helm
    date: {{ now | htmlDate }}
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  ports:
    - name: http-{{ .Values.service_port }}
      port: {{ .Values.service_port }}
      targetPort: {{ .Values.target_port }}
  selector:
    app: {{ .Release.Name }}
---
